#!/bin/bash

if [ "$(command -v brew)" ]; then
    package_manager="brew"
elif [ "$(command -v dnf)" ]; then
    package_manager="dnf"
elif [ "$(command -v yum)" ]; then
    package_manager="yum"
elif [ "$(command -v apt)" ]; then
    package_manager="apt"
elif [ "$(command -v opkg)" ]; then
    package_manager="opkg"
elif [ "$(command -v apk)" ]; then
    package_manager="apk"
else
    echo "Only support following backend package managers: dnf, yum, apt, brew, opkg(Entware) and apk(for Alpine Linux)";
    exit 1;
fi;

function ensure_yum_utils() {
    if [ ! "$(command -v repoquery)" ]; then
        if command -v dnf; then
            sudo dnf install -y yum-utils
        elif command -v yum; then
            sudo yum install -y yum-utils
        fi;
    fi;
}

function ensure_apt_file() {
    if [ ! "$(command -v apt-file)" ]; then
        sudo apt install -y apt-file;
    fi;
}

function package_install() {
    # install package xxx
    local packages
    packages=$(echo "$@" | cut -d ' ' -f2-)
    case "$package_manager" in
        dnf)
            sudo dnf install -y $packages;
            ;;
        yum)
            sudo yum install -y $packages;
            ;;
        apt)
            sudo apt install -y $packages;
            ;;
        brew)
            brew install $packages;
            ;;
        opkg)
            opkg install $packages;
            ;;
        apk)
            apk add --update $packages;
            ;;
        *)
            echo "command install NOT support for package manager $package_manager";
            ;;
    esac
}

function package_uninstall() {
    # remove package xxx yyy ...
    local packages
    packages=$(echo "$@" | cut -d ' ' -f2-)
    case "$package_manager" in
        dnf)
            sudo dnf remove -y $packages;
            ;;
        yum)
            sudo yum remove -y $packages;
            ;;
        apt)
            sudo apt remove $packages;
            ;;
        brew)
            brew uninstall $packages;
            ;;
        opkg)
            opkg remove $packages;
            ;;
        apk)
            apk del $packages;
            ;;
        *)
            echo "command uninstall NOT support for package manager $package_manager";
            ;;
    esac
}

function package_reinstall() {
    # remove package xxx yyy ...
    local packages
    packages=$(echo "$@" | cut -d ' ' -f2-)
    case "$package_manager" in
        dnf)
            sudo dnf reinstall -y $packages;
            ;;
        yum)
            sudo yum reinstall -y $packages;
            ;;
        apt)
            sudo apt install --reinstall -y $packages;
            ;;
        brew)
            brew reinstall $packages;
            ;;
        opkg)
            opkg install --force-reinstall $packages;
            ;;
        apk)
            apk add --update --force-overwrite $packages;
            ;;
        *)
            echo "command reinstall NOT support for package manager $package_manager";
            ;;
    esac
}

function package_purge() {
    # remove package xxx with config files
    local packages
    packages=$(echo "$@" | cut -d ' ' -f2-)
    case "$package_manager" in
        dnf|yum) # TODO should check
            shift;
	        for package in $packages
            do
                if rpm -q "$package" > /dev/null ; then
                    echo "removing config files for $package"
                    for file in $(rpm -q --configfiles "$package")
                    do
                        echo "  removing $file"
                        # rm -f $file
                    done
                    rpm -e "$package"
                else
                    echo "package $package is not installed"
                fi
	        done
            ;;
        apt)
            apt purge $packages;
            ;;
        *)
            echo "command purge NOT support for package manager $package_manager";
            ;;
    esac
}

function package_update() {
    # update metadata of package or package manager itself(e.g. brew)
    case "$package_manager" in
        dnf)
            dnf makecache;
            ;;
        yum)
            yum makecache;
            ;;
        apt)
            apt update;
            ;;
        brew)
            brew update;
            ;;
        opkg)
            opkg update;
            ;;
        apk)
            apk update;
            ;;
        *)
            echo "command update NOT support for package manager $package_manager";
            ;;
    esac
}

function package_upgrade() {
    # upgrade packages xxx yyy ...
    local packages
    packages=$(echo "$@" | cut -d ' ' -f2-)
    case "$package_manager" in
        dnf)
            sudo dnf upgrade -y $packages;
            ;;
        yum)
            sudo yum upgrade -y $packages;
            ;;
        apt)
            sudo apt upgrade $packages;
            ;;
        brew)
            brew upgrade $packages;
            ;;
        opkg)
            opkg upgrade $packages;
            ;;
        apk)
            apk add --update --upgrade $packages;
            ;;
        *)
            echo "command upgrade NOT support for package manager $package_manager";
            ;;
    esac
}

function package_cleanup() {
    # auto remove unneeded packages
    case "$package_manager" in
        dnf)
            sudo dnf autoremove;
            ;;
        yum)
            sudo yum autoremove;
            ;;
        apt)
            sudo apt autoremove;
            ;;
        brew)
            brew cleanup;
            ;;
        apk)
            apk cache clean;
            ;;
        *)
            echo "command cleanup NOT support for package manager $package_manager";
            ;;
    esac
}

function package_list() {
    # list all available packages
    case "$package_manager" in
        dnf)
            dnf list;
            ;;
        yum)
            yum list;
            ;;
        apt)
            apt list;
            ;;
        brew)
            brew search;
            ;;
        opkg)
            opkg list;
            ;;
        apk)
            apk search;
            ;;
        *)
            echo "command list NOT support for package manager $package_manager";
            ;;
    esac
}

function package_list_installed() {
    # list all installed packages
    case "$package_manager" in
        dnf)
            dnf list installed;
            ;;
        yum)
            yum list installed;
            ;;
        apt)
            apt list --installed;
            ;;
        brew)
            brew list;
            ;;
        opkg)
            opkg list-installed;
            ;;
        apk)
            apk list;
            ;;
        *)
            echo "command list NOT support for package manager $package_manager";
            ;;
    esac
}

function package_search() {
    # search package xxx
    case "$package_manager" in
        dnf)
            dnf search "$1";
            ;;
        yum)
            yum search "$1";
            ;;
        apt)
            apt search "$1";
            ;;
        brew)
            brew search "$1";
            ;;
        opkg)
            opkg find "*${1}*";
            ;;
        apk)
            apk search "$1";
            ;;
        *)
            echo "command search NOT support for package manager $package_manager";
            ;;
    esac
}

function package_info() {
    # show info of package xxx
    local packages
    packages=$(echo "$@" | cut -d ' ' -f2-)
    case "$package_manager" in
        dnf)
            dnf info $packages;
            ;;
        yum)
            yum info $packages;
            ;;
        apt)
            apt show $packages;
            ;;
        brew)
            brew info $packages;
            ;;
        opkg)
            for package in $packages
            do
                opkg info $package;
	        done
            ;;
        apk)
            apk info $packages;
            ;;
        *)
            echo "command info NOT support for package manager $package_manager";
            ;;
    esac
}

# TODO require install package first ??
function package_files() {
    # show files of package xxx
    local packages
    packages=$(echo "$@" | cut -d ' ' -f2-)
    case "$package_manager" in
        dnf|yum)
            ensure_yum_utils;
            repoquery --list $packages;
            ;;
        apt)
            ensure_apt_file;
            echo "Might take a long time..."
            apt-file list $packages; # support NOT installed packages, very slow
            # dpkg -L xxx # only support installed packages, very fast
            ;;
        brew)
            brew ls --verbose $packages;
            ;;
        opkg)
            for package in $packages
            do
                opkg files $package;
	        done
            ;;
        apk)
            # TODO require install package first
            apk info -L "$1";
            ;;
        *)
            echo "command files NOT support for package manager $package_manager";
            ;;
    esac
}

function package_provides() {
    # find package providing the file
    case "$package_manager" in
        dnf)
            dnf provides "$1";
            ;;
        yum)
            yum provides "$1";
            ;;
        apt)
            ensure_apt_file;
            echo "Might take a long time..."
            apt-file search "$1";
            ;;
        opkg)
            opkg search "*$1*";
            ;;
        *)
            echo "command provides NOT support for package manager $package_manager";
            ;;
    esac
}

function package_depends() {
    # show dependencies of package xxx
    case "$package_manager" in
        dnf|yum)
            ensure_yum_utils;
            repoquery --requires --resolve "$1";
            ;;
        apt)
            apt depends "$1";
            ;;
        brew)
            brew deps "$1";
            ;;
        opkg)
            opkg depends "$1";
            ;;
        apk)
            apk info --depends "$1";
            ;;
        *)
            echo "command depends NOT support for package manager $package_manager";
            ;;
    esac
}

function package_rdepends() {
    # show packages depend on package xxx(reverse depends)
    case "$package_manager" in
        dnf|yum)
            ensure_yum_utils;
            repoquery --query --whatrequires "$1";
            ;;
        apt)
            apt rdepends "$1";
            ;;
        brew)
            brew uses "$1";
            ;;
        opkg)
            opkg whatdepends "$1";
            ;;
        apk)
            apk info --rdepends "$1";
            ;;
        *)
            echo "command depends NOT support for package manager $package_manager";
            ;;
    esac
}

function package_backend() {
    echo "$package_manager";
}

function package_help() {
    echo "Usage: package <command>";
    echo "";
    echo "commands: ";
    echo "  install <package> [<package>]     install package";
    echo "  add <package> [<package>]         alias of command install";
    echo "  uninstall <package> [<package>]   uninstall package";
    echo "  remove <package> [<package>]      alias of command uninstall";
    echo "  delete <package> [<package>]      alias of command uninstall";
    echo "  purge <package> [<package>]       uninstall package with its config files";
    echo "  update                            update metadata of packages";
    echo "                                      or package manager itself(e.g. brew)";
    echo "  upgrade <package> [<package>]     upgrade package";
    echo "  cleanup                           auto remove unneeded packages";
    echo "  autoremove                        alias of command cleanup";
    echo "  list                              list all available packages";
    echo "  list-installed                    list installed packages";
    echo "  search <pattern>                  search package";
    echo "  find <pattern>                    alias of command search";
    echo "  show <package> [<package>]        show info of package";
    echo "  info <package> [<package>]        alias of command command show";
    echo "  files <package> [<package>]       show files of package";
    echo "  provides <file>                   find package providing the file";
    echo "  depends <package>                 show dependencies of package";
    echo "  rdepends <package>                show packages depend on package";
    echo "                                      (reverse dependencies)";
    echo "  backend                           show backend package manager";
    echo "  help                              show this help doc";
    echo "";
    echo "IMPORTANT NOTE: Only support following backend package managers: dnf, yum, apt, brew(for macOS), opkg(Entware) and apk(for Alpine Linux)";
}

case "$1" in
    install|add)
        package_install "$*";
        ;;
    uninstall|remove|delete)
        package_uninstall "$*";
        ;;
    purge)
        package_purge "$*";
        ;;
    update)
        package_update;
        ;;
    upgrade|dist-upgrade)
        package_upgrade "$*";
        ;;
    cleanup|autoremove)
        package_cleanup;
        ;;
    list)
        package_list;
        ;;
    list-installed)
        package_list_installed;
        ;;
    search|find)
        package_search "$2";
        ;;
    info|show)
        package_info "$*";
        ;;
    files)
        package_files "$*";
        ;;
    provides)
        package_provides "$2";
        ;;
    depends)
        package_depends "$2";
        ;;
    rdepends)
        package_rdepends "$2";
        ;;
    backend)
        package_backend;
        ;;
    help)
        package_help;
        ;;
    *)
        package_help;
        ;;
esac
